version: '3.7'

services:

  application:
    image: ${PROJECT}:${GIT_LOCAL_BRANCH}
    container_name: ${PROJECT}
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    expose:
      - "80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      timeout: 5s
      interval: 10s
      start_period: 5s
    networks:
      - frontend
networks:
  frontend:
    driver: "bridge"