FROM node:12-alpine

LABEL maintainer="BC Gov https://github.com/bcgov/startup-sample-project"

ENV PATH $PATH:/usr/src/app/node_modules/.bin

WORKDIR /usr/src/app

COPY package*.json ./

# Install dependencies
RUN npm ci

EXPOSE 80

CMD [ "npm", "run", "watch" ]
