FROM node:12

MAINTAINER FreshWorks <web@freshworks.io>

ENV PATH $PATH:/usr/src/app/node_modules/.bin

WORKDIR /usr/src/app

COPY package*.json ./

# Install dependencies
RUN npm ci

EXPOSE 80

CMD [ "npm", "run", "watch" ]
