name: Pull Request tools
# change to trigger a PR
on:
  pull_request:
    paths:
      - ".github/workflows/pr-tools.yaml"
      - ".github/workflows/tf-plan-tools.yaml"
      - "terraform/tools/**"

jobs:
  pr:
    name: pr_tools

    runs-on: ubuntu-22.04


    steps:
      - name: Save PR number
        working-directory: /tmp
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: /tmp/pr/
